from django.db import models

# Create your models here.

#
# class Movies herite de models.Model qui est importe depuis django.db
# a l interieur de la class: je defini mes champs sous forme d attributs
# ensuite on donne les types de nos champs, ie models.CharField(max_length=32)
# ces types sont contenus dans models sous forme de membres
# le membre CharField qui correspond au type varchar
#
class Movies(models.Model):
    title = models.CharField(max_length=64, unique=True, null=False)
    episode_nb = models.IntegerField(primary_key=True)
    opening_crawl = models.TextField(null=True)
    director = models.CharField(max_length=32, null=False)
    producer = models.CharField(max_length=128, null=False)
    release_date = models.DateField(null=False)
    def __str__(self):
        return self.title




"""
Pour appliquer ce modele a la bd, faire:

1) Verifier dans la bd que la table Movies n existe pas
    psql -U djangouser -d formationdjango -c "\d ex01_movies"

2) (d05-env) e1r12p13% ./manage.py makemigrations ex01

3) (d05-env) e1r12p13%  ./manage.py migrate

4) Verifier dans la bd que la table Movies existe maintenant
    psql -U djangouser -d formationdjango -c "\d ex01_movies"

5) REMARQUE: le nom de la table a ete precede du nom de l application !!!


================
Example video:
================
from django.db import models
class Members(models.Model):
    firstname = models.CharField(max_length=32)
    lastname = models.CharField(max_length=32)
    birthdate = models.DateField()




================
Migrations:
================
	Systeme qui permet d appliquer nos modeles et les changements sur ces modeles a notre BD
	et l effet supplementaire c est que cela va permettre de versionner tous ces chgts

(d05-video) e1r12p11% ./manage.py makemigrations video  ===> cree un fichier
Migrations for 'video':
  video/migrations/0001_initial.py
      - Create model Members

APP video: migrations/0001_initial.py:
-------------------------------------
Liste les changements que nous avons fait a la BD formationdjango


# Generated by Django 2.1.2 on 2018-10-07 15:50
from django.db import migrations, models
class Migration(migrations.Migration):
	initial = True			===> miogration initial
	dependencies = [
	]
	operations = [
		migrations.CreateModel(
			name='Members',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('firstname', models.CharField(max_length=32)),
				('lastname', models.CharField(max_length=32)),
				('birthdate', models.DateField()),
			],
		),
	]

Ensuite,il reste a appliquer cette migration car elle n a pas encore ete appliquee (c est comme git add et ensuite on fait un commit pour appliquer et versionner)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
(d05-video) e1r12p11% ./manage.py migrate
Operations to perform:
	Apply all migrations: admin, auth, contenttypes, sessions, video
Running migrations:
	Applying contenttypes.0001_initial... OK
	Applying auth.0001_initial... OK
    ...
	Applying auth.0009_alter_user_last_name_max_length... OK
	Applying sessions.0001_initial... OK
	Applying video.0001_initial... OK
(d05-video) e1r12p11% \

"""
